import Foundation

struct SentencePrompt {
    let sourceLanguage: String   // "english" or "urdu"
    let sourceText: String
}

enum SentencePrompts {

    static let all: [SentencePrompt] = englishSentences + urduSentences

    static let englishSentences: [SentencePrompt] = [
        "I am going to the masjid.",
        "She cooked very good food.",
        "He came home late.",
        "We will go tomorrow.",
        "Please give me some water.",
        "I said salaam to everyone.",
        "Did you see the book?",
        "Take this with you.",
        "I will come tomorrow.",
        "He is doing his work.",
        "How are you today?",
        "I am well, alhamdulillah.",
        "What did you eat today?",
        "She is coming right now.",
        "He went to the bazaar.",
        "Please sit here.",
        "I will give you the money.",
        "She took the book.",
        "He spoke the truth.",
        "What time is it?",
        "I do not know where he went.",
        "Where are you going now?",
        "I am going home.",
        "We eat together every day.",
        "He read the whole book.",
        "We all came together.",
        "Did you finish your work?",
        "She will see the doctor tomorrow.",
        "I am very happy today.",
        "He did not come yesterday.",
        "Please say salaam.",
        "She is my elder sister.",
        "He is my younger brother.",
        "I will do it tomorrow.",
        "Did you see my father?",
        "She went to the shop.",
        "He is reading the Quran.",
        "I took the medicine this morning.",
        "We are all well.",
        "May Allah keep you well.",
    ].map { SentencePrompt(sourceLanguage: "english", sourceText: $0) }

    static let urduSentences: [SentencePrompt] = [
        "میں مسجد جا رہا ہوں۔",
        "اس نے بہت اچھا کھانا پکایا۔",
        "وہ دیر سے گھر آیا۔",
        "ہم کل جائیں گے۔",
        "مجھے پانی دو۔",
        "میں نے سب کو سلام کیا۔",
        "کیا آپ نے کتاب دیکھی؟",
        "یہ اپنے ساتھ لے جاؤ۔",
        "میں کل آؤں گا۔",
        "وہ اپنا کام کر رہا ہے۔",
        "آج آپ کیسے ہیں؟",
        "اللہ کا شکر، میں ٹھیک ہوں۔",
        "آج آپ نے کیا کھایا؟",
        "وہ ابھی آ رہی ہے۔",
        "وہ بازار گیا۔",
        "یہاں بیٹھیں۔",
        "میں آپ کو پیسے دوں گا۔",
        "اس نے الماری سے کتاب لی۔",
        "اس نے سچ کہا۔",
        "کتنے بجے ہیں؟",
        "مجھے نہیں معلوم وہ کہاں گیا۔",
        "آپ ابھی کہاں جا رہے ہیں؟",
        "میں گھر جا رہا ہوں۔",
        "ہم روز ساتھ کھانا کھاتے ہیں۔",
        "اس نے پوری کتاب پڑھی۔",
        "ہم سب ساتھ آئے۔",
        "کیا آپ نے اپنا کام ختم کیا؟",
        "وہ کل ڈاکٹر سے ملے گی۔",
        "میں آج بہت خوش ہوں۔",
        "وہ کل نہیں آیا۔",
        "سلام دو۔",
        "وہ میری بڑی بہن ہے۔",
        "وہ میرا چھوٹا بھائی ہے۔",
        "میں یہ کل کروں گا۔",
        "کیا آپ نے میرے ابو کو دیکھا؟",
        "وہ دکان گئی۔",
        "وہ قرآن پڑھ رہا ہے۔",
        "میں نے آج صبح دوائی لی۔",
        "ہم سب ٹھیک ہیں۔",
        "اللہ آپ کو سلامت رکھے۔",
    ].map { SentencePrompt(sourceLanguage: "urdu", sourceText: $0) }
}
